### ISSUE TITLE
milestone

### ISSUE THREAD

**Issue by christofs** [cligs/toolbox#10]
Offenbar haben wir vergessen, das "milestone" Element zuzulassen, mit den @type-Werten: space, line, asterisk, other. So hatten wir es doch besprochen, oder? @hennyu, könntest du das mal prüfen und ggfs. noch aufnehmen? Danke!

**Comment by hennyu** [comment]
Hallo Christof,
milestone war schon erlaubt, mit den Attributen @rend und @type. Aber es gab noch keine Werteliste, das habe ich ergänzt.
