### ISSUE TITLE
tei: author IDs

### ISSUE THREAD

**Issue by christofs** [cligs/toolbox#4]
Wenn wir verschiedene ID-Quellen verwenden (GND, VIAF, BNF, etc.), könnte das Probleme machen, wenn wir einfach das @xml:id bei "author" verwenden, weil man der Nummer ja nicht ansieht, zu welchem System sie gehört. Vielleicht ist es dann besser, es so zu machen: 

```
<author>
   <name type="full"></name>
   <name type="short"></name>
   <idno type="VIAF">68936773</idno> 
</author>
```

Vorteil: Es ist eindeutig, der Link kann automatisch generiert werden (mit der jeweils passenden base-URL, bspw. "https://viaf.org/viaf/"), und man kann theoretisch auch mehrere idnos vergeben. Dann haben wir allerdings keine eigene, interne, eindeutige xml:id für die Autoren.

**Comment by christofs** [comment]
Here is more on this, with another solution: http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-att.canonical.html (attribute ref on name with full link to identifier page)

**Comment by hennyu** [comment]
The first solution (with idno) seems better to me because the identification number is not attached to the name (as would be the case with <name ref="...">). We could have an <idno type="cligs"> like for the texts themselves if we would want our own ids.

**Comment by silviaegt** [comment]
I just found out about this Open Refine service by Roderic D. M. Page: http://iphylo.blogspot.co.uk/2013/04/reconciling-author-names-using-open.html I have not manage to make it work properly for my data, but it might give you some ideas of how to match records
