### ISSUE TITLE
Werte für Attribut @type in <q>

### ISSUE THREAD

**Issue by hennyu** [cligs/toolbox#7]
Könnten wir für @type in < q > noch folgende Werte erlauben?

- written
- soCalled

Beide sind auch von den Guidelines vorgeschlagen. Wir hatten "quotation" ergänzt. Manchmal wird aber etwas Geschriebenes aufgeführt, was nicht unbedingt als Zitat zu werten ist (z.B. eine Notiz von jemandem). Und soCalled würde ich gern verwenden, wenn etwas in Anführungszeichen steht, was der Autor/die Autorin ironisch/distanziert nennt.

**Comment by christofs** [comment]
Von mir aus gerne!
