### ISSUE TITLE
forename and surname

### ISSUE THREAD

**Issue by christofs** [cligs/toolbox#9]
Mit ist gerade aufgefallen, dass wir "forename" und "surname" erlauben; verwenden wir das beim Autorennamen? Oder sollten wir?

**Comment by hennyu** [comment]
Bisher verwenden wir das noch nicht. Brauchen wir das denn, wenn wir immer einen short-name haben?

**Comment by christofs** [comment]
Ich verwende es auch nicht, für mich ist nur der short name wichtig. Und wir haben ja die VIAF-Nummer, um präzise weitere Informationen zu finden. Insofern könnten wir darauf verzichten. Mein Vorschlag wäre, es aus dem Schema zu löschen.

**Comment by hennyu** [comment]
Habe das aus dem Schema gelöscht.
